README更新 / Webサイトに役割を委譲する
lean-ja/.github pull request #2
Opened 2023-09-12 12:19 UTC by Seasawher

@aconite-ac よろしくお願いします

2023-09-12 15:06 UTC, aconite-ac requested changes
今後の更新が不要な範囲で、lean-ja・discussion・websiteについて、説明があると分かりやすいと思います。
GitHubで初めてlean-jaを知る方にも十分な情報があり、かつ詳しい説明はwebsiteに譲ればよいので不要、とするとsuggestしたくらいの一言説明が丁度よいかなと思いました。

また、折角なので証明中の画像は掲載したままでもいい気がします。
(画像をwebsiteに移す場合はこの限りではありません。)

2023-09-12 15:06 UTC, aconite-ac commented on profile/README.md
> +* 🤙 [discussion](https://github.com/orgs/lean-ja/discussions)
```suggestion
lean-jaは，Leanに関する情報の交換と集積を目的とした日本語コミュニティです．

discussionタブでLeanに関する情報を日本語でやり取りすることができます．
* 🤙 [discussion](https://github.com/orgs/lean-ja/discussions)
```

2023-09-12 15:06 UTC, aconite-ac commented on profile/README.md
> +* 🌐 [website](https://lean-ja.github.io/)
```suggestion

Webサイトでは，Leanに関する有用なサイトや日本語情報へのリンクを収集・掲載しています．
* 🌐 [website](https://lean-ja.github.io/)
```

2023-09-13 11:01 UTC, Seasawher commented
良いと思います

2023-09-13 11:01 UTC, merged